#!/usr/bin/env python3
"""Generate the *memory-capable* Hexagon differential oracle (oracle_mem.s).

Identical in spirit to gen_oracle.py, but the wire state also carries a fixed
256-byte memory ARENA. Before each test packet the input arena bytes are copied
into `g_arena` (a .bss buffer at a link-fixed address); after the packet the
arena is captured back. Load/store test packets address the arena by setting
their base register (in the input state) to `g_arena`'s address, which the Rust
harness reads from the ELF symbol table.

Wire (little-endian):
  InCase  = u32 nwords; u32 words[4]; HexState(176); u8 arena[256]   (452 B)
  OutCase = HexState(176); u32 trapped; u32 valid; u8 arena[256]     (440 B)
"""

import sys

NOP = 0x7F00C000
ARENA_SIZE = 256

# HexState field byte offsets (must match tests/hexagon_diff.rs HexState).
O_R = 0
O_PRED = 128
O_USR = 132
O_M0 = 136
O_M1 = 140
O_GP = 144
O_CS0 = 148
O_CS1 = 152
O_SA0 = 156
O_LC0 = 160
O_SA1 = 164
O_LC1 = 168
ST_SIZE = 176

CREGS = [
    (8, O_USR), (6, O_M0), (7, O_M1), (11, O_GP), (12, O_CS0), (13, O_CS1),
    (0, O_SA0), (1, O_LC0), (2, O_SA1), (3, O_LC1), (4, O_PRED),
]

# InCase layout.
CASE_NWORDS = 0
CASE_WORDS = 4
CASE_ST = 20
CASE_ARENA = CASE_ST + ST_SIZE  # 196
CASE_SIZE = CASE_ARENA + ARENA_SIZE  # 452
# OutCase layout.
OUT_ST = 0
OUT_TRAPPED = ST_SIZE
OUT_VALID = ST_SIZE + 4
OUT_ARENA = ST_SIZE + 8  # 184
OUT_SIZE = OUT_ARENA + ARENA_SIZE  # 440


def emit(out):
    p = lambda s="": out.append(s)

    p("// AUTO-GENERATED by tools/hexagon-diff/gen_oracle_mem.py -- do not edit.")
    p("// Memory-capable Hexagon differential oracle (runs under qemu-hexagon).")
    p(".text")
    p(".globl _start")
    p("_start:")
    p("\t{ r0 = #0 }")
    p("\t{ r1 = ##g_hdr }")
    p("\t{ r2 = #8 }")
    p("\t{ call read_exact }")
    p("\t{ p0 = cmp.eq(r0,#0); if (!p0.new) jump:nt .fail }")
    p("\t{ r0 = #1 }")
    p("\t{ r1 = ##g_hdr }")
    p("\t{ r2 = #8 }")
    p("\t{ call write_exact }")
    p("\t{ r0 = memw(##g_hdr+4) }")
    p("\t{ memw(##g_rem) = r0 }")
    p(".loop:")
    p("\t{ r0 = memw(##g_rem) }")
    p("\t{ p0 = cmp.eq(r0,#0); if (p0.new) jump:nt .done }")
    p("\t{ r0 = #0 }")
    p("\t{ r1 = ##g_case }")
    p(f"\t{{ r2 = #{CASE_SIZE} }}")
    p("\t{ call read_exact }")
    p("\t{ p0 = cmp.eq(r0,#0); if (!p0.new) jump:nt .fail }")
    p("\t{ call run_case }")
    p("\t{ r0 = #0 }")
    p(f"\t{{ memw(##g_out+{OUT_TRAPPED}) = r0 }}")
    p("\t{ r0 = #1 }")
    p(f"\t{{ memw(##g_out+{OUT_VALID}) = r0 }}")
    p("\t{ r0 = #1 }")
    p("\t{ r1 = ##g_out }")
    p(f"\t{{ r2 = #{OUT_SIZE} }}")
    p("\t{ call write_exact }")
    p("\t{ p0 = cmp.eq(r0,#0); if (!p0.new) jump:nt .fail }")
    p("\t{ r0 = memw(##g_rem) }")
    p("\t{ r0 = add(r0,#-1) }")
    p("\t{ memw(##g_rem) = r0 }")
    p("\t{ jump .loop }")
    p(".done:")
    p("\t{ r0 = #0 }")
    p("\t{ r6 = #94 }")
    p("\t{ trap0(#1) }")
    p(".fail:")
    p("\t{ r0 = #1 }")
    p("\t{ r6 = #94 }")
    p("\t{ trap0(#1) }")
    p("")

    for (name, sysnr) in (("read_exact", 63), ("write_exact", 64)):
        tag = name[:2]  # 're' / 'wr'
        p(f"{name}:")
        p("\t{ r16 = r0; r17 = r1; r18 = r2 }")
        p(f".{tag}_loop:")
        p(f"\t{{ p0 = cmp.eq(r18,#0); if (p0.new) jump:nt .{tag}_ok }}")
        p("\t{ r0 = r16; r1 = r17; r2 = r18 }")
        p(f"\t{{ r6 = #{sysnr} }}")
        p("\t{ trap0(#1) }")
        p(f"\t{{ p0 = cmp.gt(r0,#0); if (!p0.new) jump:nt .{tag}_err }}")
        p("\t{ r17 = add(r17,r0) }")
        p("\t{ r18 = sub(r18,r0) }")
        p(f"\t{{ jump .{tag}_loop }}")
        p(f".{tag}_ok:")
        p("\t{ r0 = #0 }")
        p("\t{ jumpr r31 }")
        p(f".{tag}_err:")
        p("\t{ r0 = #-1 }")
        p("\t{ jumpr r31 }")
        p("")

    # word-copy loop helper, emitted inline (src=r0, dst=r1, bytes=r2).
    def copy_loop(label, src_expr, dst_expr):
        p(f"\t{{ r0 = {src_expr} }}")
        p(f"\t{{ r1 = {dst_expr} }}")
        p(f"\t{{ r2 = #{ARENA_SIZE} }}")
        p(f".{label}:")
        p(f"\t{{ p0 = cmp.eq(r2,#0); if (p0.new) jump:nt .{label}_done }}")
        p("\t{ r3 = memw(r0+#0) }")
        p("\t{ memw(r1+#0) = r3 }")
        p("\t{ r0 = add(r0,#4) }")
        p("\t{ r1 = add(r1,#4) }")
        p("\t{ r2 = add(r2,#-4) }")
        p(f"\t{{ jump .{label} }}")
        p(f".{label}_done:")

    # ----- run_case -----
    p("run_case:")
    for i in range(32):
        p(f"\t{{ memw(##g_hsave+{i*4}) = r{i} }}")
    # copy input arena -> g_arena (uses r0-r3 as scratch; input not loaded yet)
    copy_loop("ain", f"##g_case+{CASE_ARENA}", "##g_arena")
    # copy test words into the slot; NOP-fill the rest.
    p(f"\t{{ r5 = memw(##g_case+{CASE_NWORDS}) }}")
    p(f"\t{{ r4 = ##{NOP:#x} }}")
    for w in range(4):
        p(f"\t{{ p0 = cmp.gt(r5,#{w}) }}")
        p(f"\t{{ r3 = memw(##g_case+{CASE_WORDS + w*4}) }}")
        p("\t{ if (!p0) r3 = r4 }")
        p(f"\t{{ memw(##testslot+{w*4}) = r3 }}")
    p("\t{ isync }")
    for creg, off in CREGS:
        p(f"\t{{ r0 = memw(##g_case+{CASE_ST + off}) }}")
        p(f"\t{{ c{creg} = r0 }}")
    for i in list(range(1, 32)) + [0]:
        p(f"\t{{ r{i} = memw(##g_case+{CASE_ST + O_R + i*4}) }}")
    p("testslot:")
    p("\t.space 16")
    p("epilogue:")
    for i in range(32):
        p(f"\t{{ memw(##g_out+{OUT_ST + O_R + i*4}) = r{i} }}")
    for creg, off in CREGS:
        p(f"\t{{ r0 = c{creg} }}")
        p(f"\t{{ memw(##g_out+{OUT_ST + off}) = r0 }}")
    # copy g_arena -> output arena (regs already captured; reuse r0-r3).
    copy_loop("aout", "##g_arena", f"##g_out+{OUT_ARENA}")
    for i in list(range(1, 32)) + [0]:
        p(f"\t{{ r{i} = memw(##g_hsave+{i*4}) }}")
    p("\t{ jumpr r31 }")
    p("")

    p(".bss")
    p(".p2align 4")
    p("g_hdr:   .space 8")
    p("g_rem:   .space 4")
    p(".p2align 4")
    p(f"g_case:  .space {CASE_SIZE}")
    p(".p2align 4")
    p(f"g_out:   .space {OUT_SIZE}")
    p(".p2align 4")
    p("g_hsave: .space 128")
    p(".p2align 4")
    p(".globl g_arena")
    p(f"g_arena: .space {ARENA_SIZE}")
    p("")


def main():
    out = []
    emit(out)
    text = "\n".join(out) + "\n"
    if len(sys.argv) > 1:
        open(sys.argv[1], "w").write(text)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
